### PR TITLE
Fix typo at Custom word in docs

### PR DESCRIPTION
**Pull request by OtacilioN**
In ``` Components > Accordion > Custom Header & Content``` the word Custom was written as "Cusotm"

### CODE REVIEW

**Comment by OtacilioN** [comment]
Any reason for this abrupt closing pull request @SupriyaKalghatgi ?

**Comment by OtacilioN** [comment]
You are fixing things that I am reporting, but instead of approving my pull requests you are closing they and fixing by you @SupriyaKalghatgi, it does not make any sense.

**Comment by SupriyaKalghatgi** [comment]
This was duplicate PR

**Comment by OtacilioN** [comment]
What's the number of the duplicated PR? @SupriyaKalghatgi

**Pull request closed without merging**
