### PR TITLE
variables must be defined outside return statement

### PR DESCRIPTION
**Pull request by beausmith**
@Jasbir23

### CODE REVIEW

**Comment by Jasbir23** [comment]
Thanks @beausmith, changes should show up in the comming update.

**Comment by beausmith** [comment]
Thanks @Jasbir23. Question for you…

Any reason that you didn't merge this PR and [PR10](https://github.com/GeekyAnts/native-base-docs/pull/10)? 🤔 

By merging them, I get credit and it shows that I'm contributing meaningfully to community projects. 😃 

By closing them, it looks like I'm making suggestions which are rejected. 😕 

Thanks for the great library! 🌻

**Comment by Jasbir23** [comment]
@beausmith  
The changes in this **PR** had changes only in the **.md** files.
The **gitbook** project builds into html files in the **_book** folder. 
If i merge the PR, i would have to manually build the project and commit the changes.
The next time you submit a **PR,** just **build** the project once.
Thanks a lot for your input here 😃

**Comment by beausmith** [comment]
Ah-ha! Thanks @Jasbir23

**Pull request closed without merging**
